# Disciplina: Introdução a programação para geocientistas

# Aula 15 - Erros

# Exercício extra! 

Todos os códigos a seguir possuem erros. Tente identificá-los e corrigi-los em uma nova célula. O exercício vale 2 (dois) pontos extras na soma geral das notas.

## 1.

In [ ]:
def uma_funcao

    print('Eu não estou interessado em nenhuma teoria')
    print('Em nenhuma fantasia, nem no algo mais'
    print('Nem em tinta pro meu rosto ou oba oba, ou melodia
    print('Para acompanhar bocejos, sonhos matinais.')


In [23]:
def uma_funcao():

    print('Eu não estou interessado em nenhuma teoria')
    print('Em nenhuma fantasia, nem no algo mais')
    print('Nem em tinta pro meu rosto ou oba oba, ou melodia')
    print('Para acompanhar bocejos, sonhos matinais.')

## 2. 

In [ ]:
for numero in range(10):
    
    # use "a" se  "numero" for múltiplo de 3, caso contrário, use "b"
    if (Numero % 3) == 0:
        mensagem = mensagem + 'a'
    else:
        mensagem = mensagem + b

print(mensagem)


In [22]:
for numero in range(10):
    
    # use "a" se  "numero" for múltiplo de 3, caso contrário, use "b"
    if (numero % 3) == 0:
        numero = 'a'
        mensagem = numero
    else:
        numero = 'b'
        mensagem = numero

print(mensagem)

a


## 3.

In [1]:
estacoes = ['Primavera', 'Verao', 'Outono', 'Inverno']
print('Minha estação favorita é', estacoes[4])

IndexError: list index out of range

In [2]:
estacoes = ['Primavera', 'Verao', 'Outono', 'Inverno']
print('Minha estação favorita é', estacoes[3])

Minha estação favorita é Inverno


## 5.

In [3]:
a = np.arange(10)

for i in range(len(a):
    print(a[i])

SyntaxError: invalid syntax (<ipython-input-3-446c0802ea66>, line 3)

In [5]:
import numpy as np

a = np.arange(10)

for i in range(len(a)):
    print(a[i])

0
1
2
3
4
5
6
7
8
9


## 6.

In [6]:
a = np.arange(10)
b = np.arange(11)

print(a+c)

NameError: name 'c' is not defined

In [8]:
a = np.arange(10)
b = np.arange(11)

print(a,b)

[0 1 2 3 4 5 6 7 8 9] [ 0  1  2  3  4  5  6  7  8  9 10]


## 7.

In [ ]:
numeros = [1, 2, 3, 4, 5, 6]

for k in range(7):
    
    print(numeros[k)

In [11]:
numeros = [1, 2, 3, 4, 5, 6]

for k in range(6):
    
    print(numeros[k])

1
2
3
4
5
6


## 8.

In [ ]:
palavra = input(Digite uma palavra: ')

tamanho = len(palavra)
print('A palavra', palavra 'tem ', Tamanho, 'letras.')

In [12]:
palavra = input('Digite uma palavra: ')

tamanho = len(palavra)
print('A palavra', palavra, 'tem ', tamanho, 'letras.')

Digite uma palavra: programação
A palavra programação tem  11 letras.


## 9.

In [ ]:
numero = input('Digite um número qualquer: ')

if numero % 2 == 0:
print(numero, 'é par)

else:
    print(numero, 'é ímpar')
   
    

In [15]:
numero = int(input('Digite um número qualquer: '))

if numero % 2 == 0:
    print(numero, 'é par')

else:
    print(numero, 'é ímpar')

Digite um número qualquer: 8
8 é par


## 10.

In [ ]:
0y = np.linspace(1,10,10)

N = len(y

for i in(range(N)):
    Print(x+i)
        

In [19]:
y = np.linspace(1,10,10)

N = len(y)

for i in(range(N)):
    print(y+i)

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
[ 2.  3.  4.  5.  6.  7.  8.  9. 10. 11.]
[ 3.  4.  5.  6.  7.  8.  9. 10. 11. 12.]
[ 4.  5.  6.  7.  8.  9. 10. 11. 12. 13.]
[ 5.  6.  7.  8.  9. 10. 11. 12. 13. 14.]
[ 6.  7.  8.  9. 10. 11. 12. 13. 14. 15.]
[ 7.  8.  9. 10. 11. 12. 13. 14. 15. 16.]
[ 8.  9. 10. 11. 12. 13. 14. 15. 16. 17.]
[ 9. 10. 11. 12. 13. 14. 15. 16. 17. 18.]
[10. 11. 12. 13. 14. 15. 16. 17. 18. 19.]
