In [1]:
import numpy as np
import matplotlib.pyplot as plt

In [2]:
lista = [1, 2, 3, 4, 5]
lista

[1, 2, 3, 4, 5]

In [3]:
array = np.array([1.0, 2.0, 3., 4., 5.])
array

array([1., 2., 3., 4., 5.])

In [4]:
a = np.arange(1,101,2)
a

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67,
       69, 71, 73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95, 97, 99])

In [5]:
b = np.linspace(1,100,100)
b

array([  1.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,  10.,  11.,
        12.,  13.,  14.,  15.,  16.,  17.,  18.,  19.,  20.,  21.,  22.,
        23.,  24.,  25.,  26.,  27.,  28.,  29.,  30.,  31.,  32.,  33.,
        34.,  35.,  36.,  37.,  38.,  39.,  40.,  41.,  42.,  43.,  44.,
        45.,  46.,  47.,  48.,  49.,  50.,  51.,  52.,  53.,  54.,  55.,
        56.,  57.,  58.,  59.,  60.,  61.,  62.,  63.,  64.,  65.,  66.,
        67.,  68.,  69.,  70.,  71.,  72.,  73.,  74.,  75.,  76.,  77.,
        78.,  79.,  80.,  81.,  82.,  83.,  84.,  85.,  86.,  87.,  88.,
        89.,  90.,  91.,  92.,  93.,  94.,  95.,  96.,  97.,  98.,  99.,
       100.])

In [6]:
c = np.arange(0,1001,5)

In [7]:
c

array([   0,    5,   10,   15,   20,   25,   30,   35,   40,   45,   50,
         55,   60,   65,   70,   75,   80,   85,   90,   95,  100,  105,
        110,  115,  120,  125,  130,  135,  140,  145,  150,  155,  160,
        165,  170,  175,  180,  185,  190,  195,  200,  205,  210,  215,
        220,  225,  230,  235,  240,  245,  250,  255,  260,  265,  270,
        275,  280,  285,  290,  295,  300,  305,  310,  315,  320,  325,
        330,  335,  340,  345,  350,  355,  360,  365,  370,  375,  380,
        385,  390,  395,  400,  405,  410,  415,  420,  425,  430,  435,
        440,  445,  450,  455,  460,  465,  470,  475,  480,  485,  490,
        495,  500,  505,  510,  515,  520,  525,  530,  535,  540,  545,
        550,  555,  560,  565,  570,  575,  580,  585,  590,  595,  600,
        605,  610,  615,  620,  625,  630,  635,  640,  645,  650,  655,
        660,  665,  670,  675,  680,  685,  690,  695,  700,  705,  710,
        715,  720,  725,  730,  735,  740,  745,  7

In [8]:
d = np.linspace(0,200)

In [9]:
d

array([  0.        ,   4.08163265,   8.16326531,  12.24489796,
        16.32653061,  20.40816327,  24.48979592,  28.57142857,
        32.65306122,  36.73469388,  40.81632653,  44.89795918,
        48.97959184,  53.06122449,  57.14285714,  61.2244898 ,
        65.30612245,  69.3877551 ,  73.46938776,  77.55102041,
        81.63265306,  85.71428571,  89.79591837,  93.87755102,
        97.95918367, 102.04081633, 106.12244898, 110.20408163,
       114.28571429, 118.36734694, 122.44897959, 126.53061224,
       130.6122449 , 134.69387755, 138.7755102 , 142.85714286,
       146.93877551, 151.02040816, 155.10204082, 159.18367347,
       163.26530612, 167.34693878, 171.42857143, 175.51020408,
       179.59183673, 183.67346939, 187.75510204, 191.83673469,
       195.91836735, 200.        ])

In [10]:
matriz = np.array([[1, 2, 3],[4, 5, 6]])
matriz

array([[1, 2, 3],
       [4, 5, 6]])

In [11]:
matriz2 = np.array([[1, 2, 3],[4, 5, 6], [7, 8, 9]])
matriz2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [12]:
matriz2 = np.array([[1, 2, 4],
                    [4, 5, 6], 
                    [7, 8, 9]])

matriz2

array([[1, 2, 4],
       [4, 5, 6],
       [7, 8, 9]])

In [13]:
a = np.arange(1,10)
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
matriz3 = a.reshape((3,3))
matriz3

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [15]:
matriz3 = np.arange(1,10).reshape(3,3)

In [16]:
matriz3

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [17]:
np.allclose(matriz2,matriz3)

False

In [18]:
matriz3

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [19]:
np.shape(matriz)

(2, 3)